### ISSUE TITLE
Suspend Current Tab Not Working

### ISSUE THREAD

**Issue by DominusMaximus** [Hau-Hau/firefox-tab-suspender#55] opened 2019-12-26 18:23 UTC
When I right click on the active tab and choose "Suspend", nothing happens. All of the other suspend commands work. Right clicking that tab and choosing "Suspend" _while in another_ tab works though.

**Comment by Mulsiphix** [comment] 2019-12-28 17:00
Confirming that this is happening for me as well.

Firefox v71.0 (64-bit)

**Comment by ideaman924** [comment] 2019-12-29 11:33
Same problem here, Firefox v71.0, macOS 10.15.2

**Comment by DominusMaximus** [comment] 2019-12-29 14:30
Something I hadn't realized

**Comment by chamini2** [comment] 2020-01-06 17:05
Duplicate of #30

**Comment by Hau-Hau** [comment] 2020-01-14 20:56
Hello all!

New version is coming into _Firefox Browser Add-Ons_
In new version is it possible to suspend currently selected tab!

Best regards,
Michalewicz Piotr

**Closed by Hau-Hau** 2020-01-14 20:56 UTC
