### ISSUE TITLE
Tab immediatly suspends after switching to another tab

### ISSUE THREAD

**Issue by SNMetamorph** [Hau-Hau/firefox-tab-suspender#36] opened 2019-08-17 14:31 UTC
When I unfocused tab and switched to another and after only 3 seconds returned back, I noticed that first tab become suspended. This behavior seem to be caused because tab suspending timer doesn't reset when tab becomes inactive and unfocused. Today I twice faced with this bug on two differ PCs. I use last release version of this extension.

**Comment by KopfKrieg** [comment] 2019-08-23 20:28
Same issue here. I sometimes have to switch often between two tabs and this is really annoying.

**Comment by ozky84** [comment] 2019-08-28 12:49
You need to go settings and resave settings then restart browser....it should fix that problem.

**Comment by KopfKrieg** [comment] 2019-08-28 22:12
Restarting the browser is not really a solution.

**Comment by ozky84** [comment] 2019-08-29 14:21
I didn't mean only restart browser....

> You need to go settings and resave settings then restart browser....it should fix that problem.

Did you read my comment???? go settings and save them again it did fix it my local setup

I suggest restart browser when about:config or other settings have changed because it make sure they will work.

**Comment by KopfKrieg** [comment] 2019-08-30 00:22
*sighs* Yes, I have read your comment. But as I already wrote, restarting the browser is not really a solution. Let me explain…

> I didn't mean only restart browser....

And I didn't say that it's the only thing I'd do. But it's the important thing for me. My laptop usually has an uptime of a few days, and so does my browser. The add-on is only beneficial for me if it works for a prolonged time. If I have to restart the browser to make the add-on working, it's useless for me.

> You need to go settings and resave settings then restart browser....it should fix that problem.

That doesn't even make sense. I could also deactivate the add-on, reload the pages I want, and activate the add-on again. That works too, and doesn't require a browser restart, but if I have to do that, why even bother using it? It's clearly a bug.

> Did you read my comment???? go settings and save them again it did fix it my local setup

I'm pretty sure it did not "fix your local setup" because I can reproduce the issue reliable.

> I suggest restart browser when about:config or other settings have changed because it make sure they will work.

That's not how Firefox applies changes. Most of the settings work absolutely fine without a browser restart.

**Comment by Hau-Hau** [comment] 2019-09-03 15:52
Hello guys!

Yes it's bug, I also experienced this issue.
On task list it is FTS-35, I will try to investigate this issue quickly.

Best regards and thanks for reporting bug!

**Comment by Hau-Hau** [comment] 2019-10-24 13:25
#43 

Hello everyone!

Today I shipped new version (3.5.1). 
I hope that this small fix in code fix problems with suspending.
I will close this issue for now, if you guys will have still same problem please write comment then I will reopen issue.

Best regards,
Michalewicz Piotr

**Closed by Hau-Hau** 2019-10-24 13:25 UTC
